### ISSUE TITLE
COVID-19 disclaimer sticky header

### ISSUE THREAD

**Issue by alis0nc** [CityOfDetroit/route-explorer#94]
#### Description:

Considering the current service modifications and requirements for riders (sit every other seat, board rear door unless you need ramp or kneel, wear a mask) during the COVID-19 pandemic, there should be a header on ddot.info stating "COVID-19: Use transit for essential travel only. For service updates, visit RideDetroitTransit.com", or words to that effect.

**Comment by jmcbroom** [comment]
Thanks! This was closed, albeit far too late, with https://github.com/CityOfDetroit/route-explorer/pull/105
